FROM node:18-alpine

# Create app directory
WORKDIR /app

# Copy files
COPY package*.json ./
RUN npm install
COPY . .

# Expose port and run dev server
EXPOSE 3001
CMD ["npm", "run", "dev", "--", "--host"]

