name: Deploy React App to EC2 via Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e
          
          # Clone if doesn't exist
          if [ ! -d "/home/ubuntu/vite-react-app" ]; then
            git clone https://github.com/<your-username>/<your-repo>.git /home/ubuntu/vite-react-app
          fi

          cd /home/ubuntu/vite-react-app
          git pull origin main

          docker stop vite-react || true
          docker rm vite-react || true
          docker build -t vite-react .
          docker run -d -p 3001:3001 --name vite-react vite-react
        EOF
